name: run-voting-service
description: "Run voting service"

runs:
  using: "composite"
  steps:
    - name: "Install Protobuf"
      shell: bash
      run: sudo apt-get install -y protobuf-compiler
    - name: "Install go packages"
      shell: bash
      run: |
        go install -u github.com/golang/protobuf/protoc-gen-go
        go install google.golang.org/protobuf/reflect/protoreflect@v1.26.0
        go install google.golang.org/protobuf/runtime/protoimpl@v1.26.0
    - name: "Run voting service"
      shell: bash
      run: |
        make -C /emojivoto
        GRPC_PORT=8081 go run emojivoto/emojivoto-voting-svc/cmd/server.go 1>/dev/null 2>/dev/null &